name: Automated Testing & Validation
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - created

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
  test:
    needs: [cancel]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14.5
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: 25.0
          elixir-version: 1.14
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-deps-${{ hashFiles('**/mix.lock') }}-test
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: MIX_ENV=test mix deps.compile
      - run: MIX_ENV=test mix compile
      - run: mix test
  audit:
    needs: [cancel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: 25.0
          elixir-version: 1.14
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-deps-${{ hashFiles('**/mix.lock') }}-dev
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix hex.audit
  format:
    needs: [cancel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: 25.0
          elixir-version: 1.14
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-deps-${{ hashFiles('**/mix.lock') }}-dev
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix format --check-formatted
  credo:
    needs: [cancel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: 25.0
          elixir-version: 1.14
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-deps-${{ hashFiles('**/mix.lock') }}-dev
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile
      - run: mix credo
  dialyzer:
    needs: [cancel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: 25.0
          elixir-version: 1.14
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-deps-dev-${{ hashFiles('**/mix.lock') }}
      - uses: actions/cache@v2
        id: plt_cache
        with:
          path: |
            priv/plts
          key: ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt-${{ hashFiles('**/mix.lock') }}
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix dialyzer --plt
        if: steps.plt_cache.outputs.cache-hit != 'true'
      - run: mix dialyzer --format github --no-check
